name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt
          pip install -r typed_requirements.txt
      - name: Black
        run: |
          black . --check --diff --verbose
      - name: Flake8
        run: |
          flake8
      - name: isort
        run: |
          isort .
          isort --check --diff .
      - name: mypy
        run: |
          mypy --install-types --non-interactive . --strict
